CREATE TABLE NEGOTIATION
(
    ID                 BIGINT      NOT NULL,
    PRODUCT            VARCHAR(32) NOT NULL,
    CURRENCY1          VARCHAR(3),
    SIDE               BIT,
    DATE1              INT,
    SIZE1              DECIMAL(35, 15),
    SIZE2              DECIMAL(35, 15),
    AGGRESSIVE_COMPANY BIGINT,
    PASSIVE_COMPANY    BIGINT,
    FIDM_ID            BIGINT,
    HEDGE_FOR_FIDM_ID  BIGINT,
    TIME1              BIGINT,
    PRICE1             DECIMAL(35, 15),
    CONSTRAINT NEGOTIATION_PK PRIMARY KEY (ID)
);

INSERT INTO NEGOTIATION(ID, PRODUCT, CURRENCY1, SIDE, DATE1, SIZE1, SIZE2,
                        AGGRESSIVE_COMPANY, PASSIVE_COMPANY, FIDM_ID,
                        HEDGE_FOR_FIDM_ID, TIME1, PRICE1)
VALUES (1, 'TEST', 'UAH', 1, 123456789, 10000000.00, 1000000.00, 1, 2, 1, 1, 123456789, 10000000.00),
       (2, 'TEST2', 'EUR', 1, 125456789, 100.00, 1000.00, 1, 2, 1, 1, 125456789, 1000.00);

CREATE TABLE MID_MATCH_STRATEGY
(	"ID" BIGINT NOT NULL,
     "NEGOTIATION_ID" BIGINT NOT NULL,
     "SYMBOL" VARCHAR(6) NOT NULL,
     "STRATEGY_TYPE" INT NOT NULL,
     "STRATEGY_SOURCE" INT NOT NULL,
     "NEAR_LEG_TENOR" VARCHAR(10) NOT NULL,
     "FAR_LEG_TENOR" VARCHAR(10) NOT NULL,
     "SIDE" BIT NOT NULL,
     "OWNER" BIGINT NOT NULL,
     "SPOT_SENSITIVITY_PRICE" DECIMAL(18,12),
     "IS_PARTIAL_FILL_ALLOWED"BIT DEFAULT 1 NOT NULL,
     "IS_BASE_NOTIONAL" BIT DEFAULT 1 NOT NULL,
     "IS_MARKET_MAKER_AGREEMENT" BIT,
     PRIMARY KEY ("ID")
);

INSERT INTO MID_MATCH_STRATEGY(ID, NEGOTIATION_ID, SYMBOL, STRATEGY_TYPE, STRATEGY_SOURCE,
                               NEAR_LEG_TENOR, FAR_LEG_TENOR, SIDE, OWNER, SPOT_SENSITIVITY_PRICE,
                               IS_PARTIAL_FILL_ALLOWED, IS_BASE_NOTIONAL, IS_MARKET_MAKER_AGREEMENT)
VALUES (1, 1, 'TEST', 1, 1, 'SMTHNG', 'SMSELSE', 1, 1, 10000.2, 1, 1, 1),
       (2, 2, 'TEST2', 1, 1, 'SMTHNG2','SMSELSE2', 1, 1,100000.3, 1,1,0);
